### ISSUE TITLE
ERROR, Missing credentials in config

### ISSUE THREAD

**Issue by redbull05689** [DNXLabs/terraform-aws-eks-external-secrets#8]
### Contact Details (optional)

redbull05689@gmail.com

### Description. What happened?

A bug happened!
I get the following errors in the log and ExternalSecret resourse cant interact woth secretsmanager
`
{"level":30,"message_time":"2022-02-04T12:41:06.340Z","pid":27,"hostname":"kubernetes-external-secrets-84cd44f76c-h8w4h","msg":"fetching secret property hello-service/password1 with role: arn:aws:iam::837464780530:role/EKSCLUSTERNAME-external-secrets in region: us-east-1"}
{"level":50,"message_time":"2022-02-04T12:41:42.047Z","pid":27,"hostname":"kubernetes-external-secrets-84cd44f76c-h8w4h","payload":{"message":"Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1","errno":"EAI_AGAIN","code":"CredentialsError","syscall":"getaddrinfo","hostname":"sts.us-east-1.amazonaws.com","region":"us-east-1","retryable":true,"time":"2022-02-04T12:41:42.047Z","originalError":{"message":"Could not load credentials from ChainableTemporaryCredentials","errno":"EAI_AGAIN","code":"CredentialsError","syscall":"getaddrinfo","hostname":"sts.us-east-1.amazonaws.com","region":"us-east-1","retryable":true,"time":"2022-02-04T12:41:42.047Z","originalError":{"message":"getaddrinfo EAI_AGAIN sts.us-east-1.amazonaws.com","errno":"EAI_AGAIN","code":"NetworkingError","syscall":"getaddrinfo","hostname":"sts.us-east-1.amazonaws.com","region":"us-east-1","retryable":true,"time":"2022-02-04T12:41:42.047Z"}}},"msg":"failure while polling the secret default/hello-service"}
{"level":30,"message_time":"2022-02-04T12:41:42.070Z","pid":27,"hostname":"kubernetes-external-secrets-84cd44f76c-h8w4h","msg":"stopping poller for default/hello-service"}
`

### Steps to reproduce

Install on EKS fargate this module

### Expected behavior

ERROR, Missing credentials in config, if using AWS_CONFIG_FILE

### Actual behavior

ERROR, Missing credentials in config, if using AWS_CONFIG_FILE

### Occurrence

Frequently

### Relevant log output

```shell
ERROR, Missing credentials in config, if using AWS_CONFIG_FILE
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brunodasilvalenga** [comment]
Hey @redbull05689 I will close the issue as it looks like is an error on the application side.
