### ISSUE TITLE
Upgrade aws provider version to latest

### ISSUE THREAD

**Issue by Bernix01** [DNXLabs/terraform-aws-eks-external-secrets#9]
### Summary

Please consider updating the aws provider version.

### Motivation

To use latest aws provider version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mkochco** [comment]
👍 - I believe this module cannot be used in with terraform that manages EKS clusters on Kubernetes 1.23 and above.  Specifically, [terraform-aws-eks](https://github.com/terraform-aws-modules/terraform-aws-eks) requires `hashicorp/aws` >= 4.0.0 and this module requires `hashicorp/aws` < 4.0.0

**Comment by mkochco** [comment]
@Looks like an Pull Request exists for removing the `< 4.0.0` restriction.  https://github.com/DNXLabs/terraform-aws-eks-external-secrets/pull/11

@adenot @mvsnogueira-dnx Is there a reason that can't be merged?

**Comment by brunodasilvalenga** [comment]
Hey @mkochco, no locks to have it approved! I have done it. Thanks for pointing that out.

Approved:
https://github.com/DNXLabs/terraform-aws-eks-external-secrets/pull/11

New version:
https://github.com/DNXLabs/terraform-aws-eks-external-secrets/releases/tag/2.1.0

I will then close the issue.
